#!/usr/bin/env python3
"""Build scaled workload-derived CLPD replay counts from gem5 COPPER counters."""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "research" / "results"
SOURCE = RESULTS / "copper_prefetch_traffic_overhead_20260616.csv"
OUT_JSON = RESULTS / "copper_clpd_workload_replay_counts_20260619.json"
OUT_CSV = RESULTS / "copper_clpd_workload_replay_counts_20260619.csv"
OUT_SVH = RESULTS / "copper_clpd_workload_replay_counts_20260619.svh"
MAX_REPLAY_OPS = 120_000
POLICY = "copper_clpd64k_peb"
DEFAULT_SEED = 12648430


def as_int(row: dict[str, str], key: str) -> int:
    raw = row.get(key, "0") or "0"
    return int(float(raw))


def scaled_count(value: int, scale: float) -> int:
    if value <= 0:
        return 0
    return max(1, int(round(value * scale)))


def main() -> None:
    rows = list(csv.DictReader(SOURCE.open(newline="")))
    selected = [r for r in rows if r["policy"] == POLICY]
    if not selected:
        raise SystemExit(f"no rows for {POLICY}")

    raw = {
        "learned_proofs": sum(as_int(r, "learnedProofs") for r in selected),
        "allowed_candidates": sum(as_int(r, "allowedCandidates") for r in selected),
        "blocked_no_provenance": sum(as_int(r, "blockedNoProvenance") for r in selected),
        "target_line_witness_misses": sum(as_int(r, "targetLineWitnessMisses") for r in selected),
        "pointer_like_candidates": sum(as_int(r, "pointerLikeCandidates") for r in selected),
        "pf_issued": sum(as_int(r, "pfIssued") for r in selected),
        "pf_useful": sum(as_int(r, "pfUseful") for r in selected),
        "boundary_authority_entries_dropped": sum(as_int(r, "boundaryAuthorityEntriesDropped") for r in selected),
    }

    replay_raw_total = (
        raw["learned_proofs"]
        + raw["allowed_candidates"]
        + raw["blocked_no_provenance"]
        + raw["target_line_witness_misses"]
    )
    scale = min(1.0, MAX_REPLAY_OPS / replay_raw_total)
    replay = {
        "commit_ops": scaled_count(raw["learned_proofs"], scale),
        "allow_queries": scaled_count(raw["allowed_candidates"], scale),
        "block_queries": scaled_count(raw["blocked_no_provenance"], scale),
        "fault_queries": scaled_count(raw["target_line_witness_misses"], scale),
    }
    # Keep the exact requested cap by shaving largest bucket if rounding overflows.
    total = sum(replay.values())
    if total > MAX_REPLAY_OPS:
        largest = max(replay, key=replay.get)
        replay[largest] -= total - MAX_REPLAY_OPS

    payload = {
        "source_csv": str(SOURCE.relative_to(ROOT)),
        "policy": POLICY,
        "workload_rows": len(selected),
        "max_replay_ops": MAX_REPLAY_OPS,
        "scale_factor": scale,
        "raw": raw,
        "replay": replay,
        "replay_total_ops": sum(replay.values()),
        "workloads": [
            {
                "workload": r["workload"],
                "learned_proofs": as_int(r, "learnedProofs"),
                "allowed_candidates": as_int(r, "allowedCandidates"),
                "blocked_no_provenance": as_int(r, "blockedNoProvenance"),
                "target_line_witness_misses": as_int(r, "targetLineWitnessMisses"),
            }
            for r in selected
        ],
    }
    OUT_JSON.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    with OUT_CSV.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["field", "raw_count", "replay_count", "scale_factor"])
        writer.writerow(["learned_proofs/commit_ops", raw["learned_proofs"], replay["commit_ops"], scale])
        writer.writerow(["allowed_candidates/allow_queries", raw["allowed_candidates"], replay["allow_queries"], scale])
        writer.writerow(["blocked_no_provenance/block_queries", raw["blocked_no_provenance"], replay["block_queries"], scale])
        writer.writerow(
            [
                "target_line_witness_misses/fault_queries",
                raw["target_line_witness_misses"],
                replay["fault_queries"],
                scale,
            ]
        )
        writer.writerow(["total_replay_driver_ops", replay_raw_total, sum(replay.values()), scale])

    OUT_SVH.write_text(
        "\n".join(
            [
                "// Generated by research/build_copper_workload_clpd_replay.py",
                f"localparam int DEFAULT_COMMIT_OPS = {replay['commit_ops']};",
                f"localparam int DEFAULT_ALLOW_QUERIES = {replay['allow_queries']};",
                f"localparam int DEFAULT_BLOCK_QUERIES = {replay['block_queries']};",
                f"localparam int DEFAULT_FAULT_QUERIES = {replay['fault_queries']};",
                f"localparam int DEFAULT_SOURCE_ROWS = {len(selected)};",
                f"localparam int DEFAULT_RAW_TOTAL = {replay_raw_total};",
                f"localparam int DEFAULT_SCALED_TOTAL = {sum(replay.values())};",
                f"localparam int DEFAULT_REPLAY_SEED = {DEFAULT_SEED};",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(OUT_JSON)
    print(OUT_CSV)
    print(OUT_SVH)


if __name__ == "__main__":
    main()
