source research/vivado_tclstore_bootstrap.tcl
read_verilog -sv research/copper_amba_sari_frontdoor.sv
read_verilog -sv research/copper_amba_sari_frontdoor_regslice.sv
read_xdc research/copper_clpd_constraints.xdc
synth_design -top copper_amba_sari_frontdoor_regslice -part xc7a35tcpg236-1
report_utilization -file research/results/copper_amba_sari_frontdoor_regslice_utilization.rpt
report_timing_summary -file research/results/copper_amba_sari_frontdoor_regslice_timing.rpt
write_checkpoint -force research/results/copper_amba_sari_frontdoor_regslice_synth.dcp
quit
