read_verilog -sv research/copper_stream_table_gate.sv
read_xdc research/copper_stream_table_constraints.xdc
synth_design -top copper_stream_table_gate -part xc7a35tcpg236-1
report_utilization -file research/copper_stream_table_utilization.rpt
report_timing_summary -file research/copper_stream_table_timing.rpt
write_checkpoint -force research/copper_stream_table_synth.dcp
quit
